In [4]:
import polars as pl
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pl.read_parquet("../data/base_modelado.parquet")

In [6]:
print(df.shape)

(40521392, 24)

In [7]:
df.schema

Schema([('id_sensor', Int32),
        ('id_fecha', Date),
        ('hora', Int32),
        ('intensidad_media', Float64),
        ('intensidad_max', Float64),
        ('intensidad_min', Float64),
        ('ocupacion_media', Float64),
        ('ocupacion_max', Float64),
        ('velocidad_media', Float64),
        ('velocidad_min', Float64),
        ('num_mediciones', Int64),
        ('num_error_E', Float64),
        ('porcentaje_calidad', Float64),
        ('año', Int64),
        ('mes', Int64),
        ('nombre_mes', String),
        ('trimestre', Int64),
        ('dia', Int64),
        ('dia_semana', Int64),
        ('fin_semana', Boolean),
        ('tipo_elem', String),
        ('distrito', Int32),
        ('latitud', Float64),
        ('longitud', Float64)])

In [8]:
df.head()

shape: (5, 24)
┌───────────┬────────────┬──────┬───────────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ id_sensor ┆ id_fecha   ┆ hora ┆ intensidad_me ┆ … ┆ tipo_elem ┆ distrito ┆ latitud   ┆ longitud  │
│ ---       ┆ ---        ┆ ---  ┆ dia           ┆   ┆ ---       ┆ ---      ┆ ---       ┆ ---       │
│ i32       ┆ date       ┆ i32  ┆ ---           ┆   ┆ str       ┆ i32      ┆ f64       ┆ f64       │
│           ┆            ┆      ┆ f64           ┆   ┆           ┆          ┆           ┆           │
╞═══════════╪════════════╪══════╪═══════════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 1001      ┆ 2026-04-18 ┆ 2    ┆ 0.0           ┆ … ┆ other     ┆ 10       ┆ 40.409729 ┆ -3.740786 │
│ 1001      ┆ 2026-04-21 ┆ 2    ┆ 0.0           ┆ … ┆ other     ┆ 10       ┆ 40.409729 ┆ -3.740786 │
│ 1001      ┆ 2026-04-21 ┆ 6    ┆ 0.0           ┆ … ┆ other     ┆ 10       ┆ 40.409729 ┆ -3.740786 │
│ 1002      ┆ 2026-04-16 ┆ 10   ┆ 0.0           ┆ … ┆ other     ┆ 10       ┆ 40.40803  ┆ -3.74376  │
│ 1002      ┆ 2026-04-17 ┆ 21   ┆ 0.0           ┆ … ┆ other     ┆ 10       ┆ 40.40803  ┆ -3.74376  │
└───────────┴────────────┴──────┴───────────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [9]:
df.describe()

shape: (9, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ id_sensor ┆ id_fecha  ┆ hora      ┆ … ┆ tipo_elem ┆ distrito  ┆ latitud   ┆ longitud │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆ str       ┆ f64       ┆   ┆ str       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.0521392 ┆ 40521392  ┆ 4.0521392 ┆ … ┆ 40521392  ┆ 4.0521392 ┆ 4.0521392 ┆ 4.052139 │
│           ┆ e7        ┆           ┆ e7        ┆   ┆           ┆ e7        ┆ e7        ┆ 2e7      │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0.0       ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 6794.1558 ┆ 2025-12-3 ┆ 11.520612 ┆ … ┆ null      ┆ 10.287664 ┆ 40.430422 ┆ -3.68403 │
│           ┆ 99        ┆ 0 16:06:5 ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│           ┆           ┆ 6.105902  ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 2677.6982 ┆ null      ┆ 6.917672  ┆ … ┆ null      ┆ 5.38041   ┆ 0.038802  ┆ 0.042648 │
│           ┆ 22        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 1001.0    ┆ 2025-07-0 ┆ 0.0       ┆ … ┆ M30       ┆ 0.0       ┆ 40.332454 ┆ -3.83688 │
│           ┆           ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│ 25%       ┆ 4693.0    ┆ 2025-09-3 ┆ 6.0       ┆ … ┆ null      ┆ 6.0       ┆ 40.39921  ┆ -3.71253 │
│           ┆           ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ 50%       ┆ 5989.0    ┆ 2025-12-3 ┆ 12.0      ┆ … ┆ null      ┆ 10.0      ┆ 40.43189  ┆ -3.68692 │
│           ┆           ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ 10111.0   ┆ 2026-04-0 ┆ 18.0      ┆ … ┆ null      ┆ 15.0      ┆ 40.459606 ┆ -3.65648 │
│           ┆           ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ max       ┆ 11541.0   ┆ 2026-06-3 ┆ 23.0      ┆ … ┆ other     ┆ 21.0      ┆ 40.515611 ┆ -3.55162 │
│           ┆           ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆ 3        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘