In [13]:
import polars as pl
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
df = pl.read_parquet("../data/gold/base_modelado.parquet")

In [15]:
print(df.shape)

(40463375, 24)

In [16]:
df.schema

Schema([('id_sensor', Int32),
        ('id_fecha', Date),
        ('hora', Int32),
        ('intensidad_media', Float64),
        ('intensidad_max', Float64),
        ('intensidad_min', Float64),
        ('ocupacion_media', Float64),
        ('ocupacion_max', Float64),
        ('velocidad_media', Float64),
        ('velocidad_min', Float64),
        ('num_mediciones', Int64),
        ('num_error_E', Float64),
        ('porcentaje_calidad', Float64),
        ('año', Int64),
        ('mes', Int64),
        ('nombre_mes', String),
        ('trimestre', Int64),
        ('dia', Int64),
        ('dia_semana', Int64),
        ('fin_semana', Boolean),
        ('distrito', Int32),
        ('latitud', Float64),
        ('longitud', Float64),
        ('es_m30', Int8)])

In [17]:
df.head()

shape: (5, 24)
┌───────────┬────────────┬──────┬──────────────────┬───┬──────────┬───────────┬───────────┬────────┐
│ id_sensor ┆ id_fecha   ┆ hora ┆ intensidad_media ┆ … ┆ distrito ┆ latitud   ┆ longitud  ┆ es_m30 │
│ ---       ┆ ---        ┆ ---  ┆ ---              ┆   ┆ ---      ┆ ---       ┆ ---       ┆ ---    │
│ i32       ┆ date       ┆ i32  ┆ f64              ┆   ┆ i32      ┆ f64       ┆ f64       ┆ i8     │
╞═══════════╪════════════╪══════╪══════════════════╪═══╪══════════╪═══════════╪═══════════╪════════╡
│ 1001      ┆ 2026-04-18 ┆ 2    ┆ 0.0              ┆ … ┆ 10       ┆ 40.409729 ┆ -3.740786 ┆ 0      │
│ 1001      ┆ 2026-04-21 ┆ 2    ┆ 0.0              ┆ … ┆ 10       ┆ 40.409729 ┆ -3.740786 ┆ 0      │
│ 1001      ┆ 2026-04-21 ┆ 6    ┆ 0.0              ┆ … ┆ 10       ┆ 40.409729 ┆ -3.740786 ┆ 0      │
│ 1002      ┆ 2026-04-16 ┆ 10   ┆ 0.0              ┆ … ┆ 10       ┆ 40.40803  ┆ -3.74376  ┆ 0      │
│ 1002      ┆ 2026-04-17 ┆ 21   ┆ 0.0              ┆ … ┆ 10       ┆ 40.40803  ┆ -3.74376  ┆ 0      │
└───────────┴────────────┴──────┴──────────────────┴───┴──────────┴───────────┴───────────┴────────┘

In [18]:
df.describe()

shape: (9, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ id_sensor ┆ id_fecha  ┆ hora      ┆ … ┆ distrito  ┆ latitud   ┆ longitud  ┆ es_m30   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆ str       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.0463375 ┆ 40463375  ┆ 4.0463375 ┆ … ┆ 4.0463375 ┆ 4.0463375 ┆ 4.0463375 ┆ 4.046337 │
│           ┆ e7        ┆           ┆ e7        ┆   ┆ e7        ┆ e7        ┆ e7        ┆ 5e7      │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 6793.5993 ┆ 2025-12-3 ┆ 11.525296 ┆ … ┆ 10.28845  ┆ 40.430389 ┆ -3.684029 ┆ 0.062707 │
│           ┆ 56        ┆ 0 16:17:0 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 8.472825  ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 2677.8912 ┆ null      ┆ 6.916483  ┆ … ┆ 5.382277  ┆ 0.038799  ┆ 0.04266   ┆ 0.242436 │
│           ┆ 71        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 1001.0    ┆ 2025-07-0 ┆ 0.0       ┆ … ┆ 0.0       ┆ 40.332454 ┆ -3.836886 ┆ 0.0      │
│           ┆           ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 4693.0    ┆ 2025-09-3 ┆ 6.0       ┆ … ┆ 6.0       ┆ 40.399208 ┆ -3.712542 ┆ 0.0      │
│           ┆           ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ 5987.0    ┆ 2025-12-3 ┆ 12.0      ┆ … ┆ 10.0      ┆ 40.431868 ┆ -3.686946 ┆ 0.0      │
│           ┆           ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ 10111.0   ┆ 2026-04-0 ┆ 18.0      ┆ … ┆ 15.0      ┆ 40.459598 ┆ -3.65645  ┆ 0.0      │
│           ┆           ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 11541.0   ┆ 2026-06-3 ┆ 23.0      ┆ … ┆ 21.0      ┆ 40.515611 ┆ -3.551623 ┆ 1.0      │
│           ┆           ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘